modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Mrbysco/TieredTridents/issues"
license="MIT"

[[mods]]
modId="tieredtridents"
version="${file.jarVersion}"
displayName="Tiered Tridents"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tiered-tridents"
authors="Mrbysco"
credits="Nekomaster for the idea"
description='''
Adds ore-tiered Tridents, along with some extras! 
'''
[[dependencies.tieredtridents]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.tieredtridents]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"