modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/TieredTridents/issues"
license="MIT"

[[mods]]
modId="tieredtridents"
version="${file.jarVersion}"
displayName="Tiered Tridents"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tiered-tridents"
authors="Mrbysco"
credits="Nekomaster for the idea"
description='''
Adds ore-tiered Tridents, along with some extras! 
'''
[[dependencies.tieredtridents]]
modId="minecraft"
type="required"
versionRange="[1.21.11,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.tieredtridents]]
modId="neoforge"
type="required"
versionRange="[21.11.0-beta,)"
ordering="NONE"
side="BOTH"